version: "3.9"
services:
   nginx:
     build: ./nginx/
     ports:
       - 80:80

     volumes:
         - ./php-project/:/var/www/html/

   php:
     build: ./php-project/
     expose:
       - 9000
     volumes:
        - ./php-project/:/var/www/html/